question_data = [
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "Nintendo started out as a playing card manufacturer.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                           "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
         "question": "Seoul is the capital of North Korea.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
         "question": "The Pythagorean theorem states that the square of the hypotenuse is equal to the product of the squares of the other two sides.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "Leonardo DiCaprio won an Oscar for Best Actor in 2004&#039;s &quot;The Aviator&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "History", "type": "boolean", "difficulty": "medium",
         "question": "The first televised presidential debate was between Jimmy Carter and Gerald Ford.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "The &quot;Gympie Stinger&quot; is the deadliest plant in the world.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                          "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "medium",
         "question": "In the game &quot;Racko&quot; you may pick up ANY card from the discard pile.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
         "question": "111,111,111 x 111,111,111 = 12,345,678,987,654,321", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "&quot;Half-Life 2&quot; runs on the Source Engine.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
         "question": "The first &quot;Metal Gear&quot; game was released for the PlayStation 1.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                           "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
                                           "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "History", "type": "boolean", "difficulty": "hard",
         "question": "The fourth funnel of the RMS Titanic was fake designed to make the ship look more powerful and symmetrical.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
         "question": "The television show Doctor Who first aired in 1963.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                           "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
         "question": "TF2: Sentry rocket damage falloff is calculated based on the distance between the sentry and the enemy, not the engineer and the enemy",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "TF2: The Heavy&#039;s voice actor, Gary Schwartz, voices the Demoman as well ",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
         "question": "In the TV series Red Dwarf, Kryten&#039;s full name is Kryten 2X4B-523P.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In Sonic the Hedgehog universe, Tails&#039; real name is Miles Prower.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Politics", "type": "boolean", "difficulty": "medium",
                                           "question": "During the 2016 United States presidential election, the State of California possessed the most electoral votes, having 55.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                           "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Politics", "type": "boolean", "difficulty": "hard",
         "question": "Joko Widodo has appeared in the cover of a TIME magazine.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                           "question": "In the periodic table, Potassium&#039;s symbol is the letter K.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
         "question": "An Astronomical Unit is the distance between Earth and the Moon.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                          "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
         "question": "Druid is a mage class in &quot;Log Horizon&quot;.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "History", "type": "boolean", "difficulty": "easy",
                                          "question": "Kublai Khan is the grandchild of Genghis Khan?",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium", "question": "Sugar contains fat.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Sports", "type": "boolean", "difficulty": "medium",
         "question": "Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Rich Uncle Pennybags&quot; from the board game &quot;Monopoly&quot; wears a monocle.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
         "question": "Nick Mason is the only member to appear on every Pink Floyd album.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
         "question": "In the &quot;To Love-Ru&quot; series, Golden Darkness is sent to kill Lala Deviluke.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
         "question": "The sum of any two odd integers is odd.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In &quot;Need for Speed: Porsche Unleashed&quot;, the player can only drive cars manufactured by Porsche.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
         "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "medium",
         "question": "Donald Duck played the role of Bob Cratchit in Disney&#039;s 1983 adaptation of A Christmas Carol.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Animals", "type": "boolean", "difficulty": "medium",
         "question": "You can tell the age of a ladybird by counting the spots on his back.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                          "question": "John Williams composed the music for &quot;Star Wars&quot;.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Art", "type": "boolean", "difficulty": "hard",
         "question": "The Statue of Liberty&#039;s official name is &ldquo;Liberty Enlightening the World&rdquo;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "In the game &quot;Until Dawn&quot; Emily is the only playable character who can be killed by another playable character directly.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
         "question": "The Harry Potter series of books, combined, are over 1,000,000 words in length.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Tachycardia&quot; or &quot;Tachyarrhythmia&quot; refers to a resting heart-rate near or over 100 BPM.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Each piece in Tetris is called a tetris.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.",
         "correct_answer": "False", "incorrect_answers": ["True"]}
]
